apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-image
  namespace: npm-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-image
  template:
    metadata:
      labels:
        app: fe-image
    spec:
      containers:
      - name: fe-image
        image: asia-southeast1-docker.pkg.dev/crested-aquifer-485713-v5/docker-repo/fe-image:tag1
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        ports:
        - containerPort: 3300
        envFrom:
        - configMapRef:
            name: fe-config