server {
    listen 8080;
    server_name localhost;

    # Bảo mật Headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';";
    add_header Referrer-Policy "no-referrer-when-downgrade";

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html; # Hỗ trợ Vue Router (History mode)
    }

    # Tối ưu hóa nén Gzip để tăng tốc độ tải trang
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Chặn truy cập vào các file ẩn (như .env hoặc .git)
    location ~ /\. {
        deny all;
    }
}