apiVersion: v1
kind: Service
metadata:
  name: fe-service
  namespace: npm-fe
spec:
  selector:
    app: fe-image
  ports:
    - protocol: TCP
      port: 3300
      targetPort: 3300
  type: LoadBalancer
