apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: news-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: us-central1-docker.pkg.dev/news-system-cloud-project/docker-repo/consumer:tag1
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        envFrom:
        - configMapRef:
            name: consumer-config