apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: us-central1-docker.pkg.dev/news-database-55/docker-repo/consumer:tag1
        envFrom:
        - configMapRef:
            name: consumer-config