apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-image
  namespace: flask-be
spec:
  replicas: 3
  selector:
    matchLabels:
      app: be-image
  template:
    metadata:
      labels:
        app: be-image
    spec:
      containers:
      - name: be-image
        image: us-central1-docker.pkg.dev/news-system-cloud-project/docker-repo/be-image:tag1
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3030
        envFrom:
        - configMapRef:
            name: be-config