apiVersion: v1
kind: Service
metadata:
  name: be-service
  namespace: news-system
spec:
  selector:
    app: be-image
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
