apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-hs
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:4.2.0-rc3
          command:
            - "/bin/bash"
            - "-c"
            - |
              HOSTNAME=$(hostname)
              export KAFKA_NODE_ID=${HOSTNAME##*-}
              echo "Starting Kafka with Node ID: $KAFKA_NODE_ID"
              exec /opt/kafka/bin/kafka-server-start.sh /etc/kafka/docker/server.properties \
              --override node.id=$KAFKA_NODE_ID \
              --override process.roles=broker,controller \
              --override controller.quorum.voters="0@kafka-0.kafka-hs:9093,1@kafka-1.kafka-hs:9093,2@kafka-2.kafka-hs:9093" \
              --override listeners=PLAINTEXT://:9092,CONTROLLER://:9093 \
              --override advertised.listeners=PLAINTEXT://$(hostname).kafka-hs:9092 \
              --override controller.listener.names=CONTROLLER \
              --override listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT \
              --override initial.broker.registration.timeout.ms=60000 \
              --override cluster.id=L69_S-K_S9id-9e_vFfW8A
          ports:
            - containerPort: 9092
              name: client
            - containerPort: 9093
              name: controller
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard-rwo
        resources:
          requests:
            storage: 10Gi
