apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-image
  namespace: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-image
  template:
    metadata:
      labels:
        app: locust-image
    spec:
      containers:
      - name: locust-image
        image: us-central1-docker.pkg.dev/news-database-55/docker-repo/locust-image:tag1
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        ports:
        - containerPort: 8089